/* Nivo rough v1 image generation: adds a small create-image action to the topic chat. */
(function () {
    function addImageAction() {
        const form = document.getElementById("topicChatForm");
        const input = document.getElementById("topicChatInput");
        if (!form || !input || document.getElementById("nivoImageButton")) return;

        const button = document.createElement("button");
        button.type = "button";
        button.id = "nivoImageButton";
        button.className = "nivo-image-button";
        button.title = "Ask Nivo to create an image";
        button.setAttribute("aria-label", "Create image with Nivo");
        button.textContent = "✦";
        form.insertBefore(button, form.lastElementChild);

        button.addEventListener("click", async () => {
            const prompt = input.value.trim();
            if (!prompt) {
                input.focus();
                input.placeholder = "Describe the image you want Nivo to create...";
                return;
            }

            const messages = document.getElementById("chatMessages");
            if (!messages) return;
            const addMessage = (role, html) => {
                const node = document.createElement("div");
                node.className = `chat-message ${role}`;
                node.innerHTML = html;
                messages.appendChild(node);
                messages.scrollTop = messages.scrollHeight;
                return node;
            };

            addMessage("user", `<strong>You</strong><p>${escapeHtml(prompt)}</p>`);
            input.value = "";
            button.disabled = true;
            const loading = addMessage("assistant", "<strong>Nivo</strong><p>Creating it…</p>");

            try {
                const response = await fetch("/api/generate-image", {
                    method: "POST",
                    headers: { "Content-Type": "application/json" },
                    body: JSON.stringify({ prompt })
                });
                if (!response.ok) {
                    let message = "Nivo could not create that image.";
                    try { message = (await response.json()).error || message; } catch {}
                    throw new Error(message);
                }
                const blob = await response.blob();
                const url = URL.createObjectURL(blob);
                loading.innerHTML = `<strong>Nivo</strong><p>Here you go ✨</p><img src="${url}" alt="Image generated by Nivo" class="nivo-generated-image">`;
            } catch (error) {
                loading.innerHTML = `<strong>Nivo</strong><p>${escapeHtml(error.message || "Nivo could not create that image right now.")}</p>`;
            } finally {
                button.disabled = false;
                messages.scrollTop = messages.scrollHeight;
            }
        });
    }

    function escapeHtml(value) {
        return String(value).replace(/&/g, "&amp;").replace(/</g, "&lt;").replace(/>/g, "&gt;").replace(/\"/g, "&quot;").replace(/'/g, "&#039;");
    }

    document.addEventListener("DOMContentLoaded", addImageAction);
})();
