/* Nivo rough v1 image generation: lets image requests route through the image endpoint. */
(function () {
    function escapeHtml(value) {
        return String(value)
            .replace(/&/g, "&amp;")
            .replace(/</g, "&lt;")
            .replace(/>/g, "&gt;")
            .replace(/\"/g, "&quot;")
            .replace(/'/g, "&#039;");
    }

    function isImageRequest(value) {
        const text = String(value || "").trim().toLowerCase();
        if (!text) return false;

        // Keep this intentionally conservative so normal Nivo conversation still
        // goes through /api/chat. These are natural image-creation requests.
        return /\b(create|generate|make|draw|render|produce)\b[\s\S]{0,80}\b(image|picture|photo|illustration|diagram|infographic|poster|visual)\b/.test(text)
            || /\b(image|picture|photo|illustration|diagram|infographic|poster|visual)\b[\s\S]{0,40}\b(of|showing|depicting)\b/.test(text)
            || /\b(show|give)\s+me\s+(an?\s+)?(image|picture|illustration|diagram|infographic)\b/.test(text);
    }

    function addMessage(messages, role, html) {
        const node = document.createElement("div");
        node.className = `chat-message ${role}`;
        node.innerHTML = html;
        messages.appendChild(node);
        messages.scrollTop = messages.scrollHeight;
        return node;
    }

    async function generateImage(prompt, input, button) {
        const messages = document.getElementById("chatMessages");
        if (!messages) return;

        addMessage(messages, "user", `<strong>You</strong><p>${escapeHtml(prompt)}</p>`);
        if (input) input.value = "";
        if (button) button.disabled = true;
        const loading = addMessage(messages, "assistant", "<strong>Nivo</strong><p>Creating it…</p>");

        try {
            const response = await fetch("/api/generate-image", {
                method: "POST",
                headers: { "Content-Type": "application/json" },
                body: JSON.stringify({ prompt })
            });

            if (!response.ok) {
                let message = "Nivo could not create that image.";
                try {
                    const data = await response.json();
                    message = data.error || message;
                } catch {}
                throw new Error(message);
            }

            const blob = await response.blob();
            const url = URL.createObjectURL(blob);
            loading.innerHTML = `<strong>Nivo</strong><p>Here you go ✨</p><img src="${url}" alt="Image generated by Nivo" class="nivo-generated-image">`;
        } catch (error) {
            loading.innerHTML = `<strong>Nivo</strong><p>${escapeHtml(error.message || "Nivo could not create that image right now.")}</p>`;
        } finally {
            if (button) button.disabled = false;
            messages.scrollTop = messages.scrollHeight;
        }
    }

    function addImageAction() {
        const form = document.getElementById("topicChatForm");
        const input = document.getElementById("topicChatInput");
        if (!form || !input || document.getElementById("nivoImageButton")) return;

        const button = document.createElement("button");
        button.type = "button";
        button.id = "nivoImageButton";
        button.className = "nivo-image-button";
        button.title = "Ask Nivo to create an image";
        button.setAttribute("aria-label", "Create image with Nivo");
        button.textContent = "✦";
        form.insertBefore(button, form.lastElementChild);

        button.addEventListener("click", async () => {
            const prompt = input.value.trim();
            if (!prompt) {
                input.focus();
                input.placeholder = "Describe the image you want Nivo to create...";
                return;
            }
            await generateImage(prompt, input, button);
        });
    }

    function installImageRouting() {
        // Capture the submit before topic-materials.js sends the same text to
        // /api/chat. Only image-intent messages are intercepted.
        document.addEventListener("submit", function (event) {
            const form = event.target;
            if (!form || form.id !== "topicChatForm") return;

            const input = document.getElementById("topicChatInput");
            const prompt = input?.value.trim() || "";
            if (!isImageRequest(prompt)) return;

            event.preventDefault();
            event.stopImmediatePropagation();
            const button = document.getElementById("nivoImageButton");
            generateImage(prompt, input, button);
        }, true);
    }

    document.addEventListener("DOMContentLoaded", function () {
        addImageAction();
        installImageRouting();
    });
})();
