document.addEventListener('DOMContentLoaded',()=>{
 const account=(()=>{try{return JSON.parse(localStorage.getItem('studyOS-account'))}catch{return null}})(); if(!account){location.replace('index.html');return}
 const subjects=window.studyOSStorage?.getSubjects?.()||{}; const subjectEntries=Object.entries(subjects);
 const steps=[...document.querySelectorAll('.pathway-step')]; let current=1; const answers={struggles:[],difficulty:null,time:null,date:'',notes:''};
 const subjectBox=document.getElementById('struggleSubjects');
 subjectBox.innerHTML=subjectEntries.length?subjectEntries.map(([id,s])=>`<button type="button" data-id="${escapeHTML(id)}">${escapeHTML(s.name)}</button>`).join(''):'<p class="muted-message">Add subjects first, then Nivora can personalize this pathway.</p>';
 subjectBox.addEventListener('click',e=>{const b=e.target.closest('button');if(!b)return;b.classList.toggle('selected');const id=b.dataset.id;answers.struggles=answers.struggles.includes(id)?answers.struggles.filter(x=>x!==id):[...answers.struggles,id]});
 function bindChoices(id,key){document.getElementById(id).addEventListener('click',e=>{const b=e.target.closest('button');if(!b)return;document.querySelectorAll(`#${id} button`).forEach(x=>x.classList.remove('selected'));b.classList.add('selected');answers[key]=b.dataset.value})}
 bindChoices('difficultyChoices','difficulty');bindChoices('timeChoices','time');
 function showStep(n){current=n;steps.forEach(s=>s.classList.toggle('active',Number(s.dataset.step)===n));document.getElementById('stepLabel').textContent=`STEP ${n} OF 4`;document.getElementById('stepProgress').style.width=`${n*25}%`;document.getElementById('backButton').disabled=n===1;document.getElementById('nextButton').textContent=n===4?'Build my pathway →':'Continue →'}
 document.getElementById('backButton').onclick=()=>{if(current>1)showStep(current-1)};
 document.getElementById('nextButton').onclick=()=>{if(current===1&&!answers.struggles.length){alert('Choose at least one subject you are struggling with.');return}if(current===2&&!answers.difficulty){alert('Choose what makes studying difficult for you.');return}if(current===3&&!answers.time){alert('Choose a realistic daily study time.');return}if(current<4){showStep(current+1);return}buildPath()};
 document.getElementById('editPathButton').onclick=()=>{document.getElementById('resultCard').classList.add('hidden');document.getElementById('assessmentCard').classList.remove('hidden');showStep(1)};
 function buildPath(){answers.date=document.getElementById('targetDate').value;answers.notes=document.getElementById('pathwayNotes').value.trim();const selected=answers.struggles.map(id=>[id,subjects[id]]).filter(x=>x[1]);const minutes=Number(answers.time||60);const topics=[];selected.forEach(([id,s])=>(s.topics||[]).forEach(t=>{const started=!!(t.started||Number(t.attempts||0)>0||Number(t.score||0)>0);const score=Number(t.score||0);let priority=0;if(!started)priority+=1;if(score<60)priority+=4;if(answers.difficulty==='basics')priority+=2;if(answers.difficulty==='problems')priority+=score<75?2:0;topics.push({subjectId:id,subjectName:s.name,name:t.name,score,started,priority})}));topics.sort((a,b)=>b.priority-a.priority);const plan=topics.slice(0,Math.max(3,Math.min(6,Math.floor(minutes/25))));if(!plan.length){selected.forEach(([id,s])=>plan.push({subjectId:id,subjectName:s.name,name:'Start with a core topic',score:0,started:false,priority:1}))}const list=document.getElementById('planList');list.innerHTML=plan.map((t,i)=>`<div class="plan-item"><span class="plan-number">${i+1}</span><div><strong>${escapeHTML(t.name)}</strong><small>${escapeHTML(t.subjectName)} · ${t.started?'Build mastery':'Start here'}</small></div><span class="plan-time">${i===0?'30 min':i<3?'25 min':'20 min'}</span></div>`).join('');document.getElementById('resultTitle').textContent=answers.date?`Your path to ${new Date(answers.date+'T12:00:00').toLocaleDateString('en-IN',{day:'numeric',month:'short'})}`:'Your first pathway is ready';document.getElementById('resultSummary').textContent=`Nivora prioritized ${answers.struggles.length} subject${answers.struggles.length===1?'':'s'} based on what you said. ${answers.difficulty==='problems'?'Extra practice is weighted toward problem-solving.':answers.difficulty==='basics'?'Foundations are weighted more heavily.':'Your plan starts with understanding and reinforcement.'}`;localStorage.setItem('nivora-learning-path',JSON.stringify({...answers,generatedAt:new Date().toISOString(),plan}));document.getElementById('assessmentCard').classList.add('hidden');document.getElementById('resultCard').classList.remove('hidden');document.getElementById('resultCard').scrollIntoView({behavior:'smooth',block:'start'})}
 function escapeHTML(v){return String(v).replace(/&/g,'&amp;').replace(/</g,'&lt;').replace(/>/g,'&gt;').replace(/"/g,'&quot;').replace(/'/g,'&#039;')}
 showStep(1);
});