const isPdfUrl = value => { try { const u=new URL(String(value||"").trim()); const p=`${u.pathname}${u.search}`.toLowerCase(); return p.includes(".pdf")||/[?&](file|format|type)=pdf(?:&|$)/i.test(u.search); } catch { return false; } };
const cleanText = value => String(value||"").replace(/<[^>]+>/g,"").replace(/&amp;/g,"&").replace(/&quot;/g,'"').replace(/&#39;/g,"'").replace(/&lt;/g,"<").replace(/&gt;/g,">").trim();
function extractModelText(r){if(!r)return "";if(typeof r.output_text==="string")return r.output_text;if(typeof r.response==="string")return r.response;if(typeof r.result?.response==="string")return r.result.response;const o=Array.isArray(r.output)?r.output:[];return o.filter(x=>x?.type==="message").flatMap(x=>Array.isArray(x.content)?x.content:[]).filter(x=>x?.type==="output_text"&&typeof x.text==="string").map(x=>x.text).join("\n");}
function extractCitations(r){const o=Array.isArray(r?.output)?r.output:[];return o.filter(x=>x?.type==="message").flatMap(x=>Array.isArray(x.content)?x.content:[]).flatMap(x=>Array.isArray(x.annotations)?x.annotations:[]).filter(x=>x?.type==="url_citation"&&x.url).map(x=>({title:x.title||"PDF study resource",url:x.url,reason:"Found by Nivo's web search."}));}
function extractJsonObject(text){if(typeof text!=="string")return null;const c=text.replace(/^```json\s*/i,"").replace(/^```\s*/i,"").replace(/\s*```$/i,"").trim();try{return JSON.parse(c);}catch{}const m=c.match(/\{[\s\S]*\}/);if(!m)return null;try{return JSON.parse(m[0]);}catch{return null;}}
function cleanTopic(topic){let s=String(topic||"").replace(/\b(semester|sem|year|course|college|university|subject|module|unit|chapter|paper|section|syllabus|curriculum)\b/gi," ");s=s.replace(/[()[\]{}|:;,]/g," ").replace(/\b(20\d{2}|19\d{2})\b/g," ").replace(/\s+/g," ").trim();return s.length>120?s.slice(0,120).trim():s;}
async function discoverPdfLinks(pageUrl){if(!/^https?:\/\//i.test(pageUrl)||isPdfUrl(pageUrl))return [];try{const r=await fetch(pageUrl,{headers:{"User-Agent":"Mozilla/5.0 Nivora/1.0"},redirect:"follow"});if(!r.ok)return [];const type=r.headers.get("content-type")||"";if(type.includes("application/pdf"))return[{title:pageUrl.split("/").pop()||"PDF resource",url:pageUrl,reason:"Direct PDF resource found by Nivo."}];if(!type.includes("text/html"))return [];const html=await r.text(),found=[],pat=/(?:href|src)=["']([^"']+)["']/gi;for(const m of html.matchAll(pat)){if(found.length>=6)break;try{const resolved=new URL(m[1],pageUrl).href;if(isPdfUrl(resolved))found.push({title:resolved.split("/").pop()?.split("?")[0]||"PDF resource",url:resolved,reason:"Direct PDF linked from a web result."});}catch{}}return found;}catch{return [];}}
export async function onRequestGet(context){try{const url=new URL(context.request.url);const subject=String(url.searchParams.get("subject")||"").trim();const topic=String(url.searchParams.get("topic")||"").trim();if(!subject||!topic)return Response.json({error:"Subject and topic are required."},{status:400});
const coreTopic=cleanTopic(topic)||topic;const query=`${coreTopic} ${subject} study notes lecture textbook filetype:pdf`;
let candidates=[];
if(context.env.AI){try{const prompt=`You are finding study PDFs for a college student. The topic label may contain irrelevant metadata such as college name, university name, semester, year, course code, chapter numbering or administrative wording. IGNORE that metadata. First identify the concise academic concept the student actually needs to study from the topic label. Then search the web for the best publicly accessible DIRECT PDF resources about that concept. Use the subject only as context. Prefer university, government, academic, textbook, lecture-note and reputable educational PDFs. Avoid generic college pages, unrelated syllabi, marketing pages and pages that merely mention the topic. Return ONLY JSON: {"core_topic":"concise concept","results":[{"title":"...","url":"https://...pdf","reason":"specific reason this PDF helps"}]}. Never invent URLs and never return a URL unless it is a real web result.`;const response=await context.env.AI.run("openai/gpt-4.1-mini",{input:`${prompt}\n\nSubject: ${subject}\nTopic label: ${topic}`,max_output_tokens:3500,tools:[{type:"web_search_preview"}]},{gateway:{id:"default"}});const parsed=extractJsonObject(extractModelText(response));if(Array.isArray(parsed?.results))candidates.push(...parsed.results.map(x=>({title:String(x.title||"PDF resource"),url:String(x.url||"").trim(),reason:String(x.reason||"Relevant PDF study resource.")})));candidates.push(...extractCitations(response));}catch(e){console.error("Nivora AI PDF search failed:",e);}}
const pageCandidates=candidates.filter(x=>x.url&&!isPdfUrl(x.url)).slice(0,8);if(pageCandidates.length){const resolved=await Promise.all(pageCandidates.map(x=>discoverPdfLinks(x.url)));resolved.flat().forEach(x=>candidates.push(x));}
if(!candidates.some(x=>isPdfUrl(x.url))&&context.env.BING_SEARCH_API_KEY){try{const r=await fetch(`https://api.bing.microsoft.com/v7.0/search?q=${encodeURIComponent(query)}&count=20&responseFilter=Webpages&textDecorations=false&safeSearch=Strict`,{headers:{"Ocp-Apim-Subscription-Key":context.env.BING_SEARCH_API_KEY}});if(r.ok){const d=await r.json();candidates.push(...(d.webPages?.value||[]).map(x=>({title:x.name||"PDF resource",url:x.url,reason:x.snippet||"Relevant PDF study resource."})));}}catch(e){console.error("Nivora Bing PDF search failed:",e);}}
if(!candidates.some(x=>isPdfUrl(x.url))){try{const r=await fetch(`https://html.duckduckgo.com/html/?q=${encodeURIComponent(query)}`,{headers:{"User-Agent":"Mozilla/5.0 Nivora/1.0"}});if(r.ok){const html=await r.text();const matches=[...html.matchAll(/<a[^>]+class=["']result__a["'][^>]+href=["']([^"']+)["'][^>]*>([\s\S]*?)<\/a>/gi)];candidates.push(...matches.map(m=>{let u=m[1];try{const x=new URL(u,"https://html.duckduckgo.com");const redirected=x.searchParams.get("uddg");if(redirected)u=decodeURIComponent(redirected);}catch{}return{title:cleanText(m[2])||"PDF resource",url:u,reason:"Relevant PDF study resource."};}));}}catch(e){console.error("Nivora DuckDuckGo PDF search failed:",e);}}
const seen=new Set();candidates=candidates.filter(x=>isPdfUrl(x.url)).filter(x=>{try{x.url=new URL(x.url).href;}catch{return false;}const k=x.url.toLowerCase();if(seen.has(k))return false;seen.add(k);return true;}).slice(0,12);if(!candidates.length)return Response.json({success:true,coreTopic,results:[],message:"No direct PDF resources were found for this topic."});
if(context.env.AI&&candidates.length>1){try{const ranking=`Rank these PDF resources for the core academic concept "${coreTopic}". Ignore college, semester, year and course metadata. Prefer exact concept relevance and credible academic sources. Return ONLY JSON {"indexes":[0,1,2,3,4]}.\n\n${candidates.map((c,i)=>`${i}: ${c.title}\n${c.url}\n${c.reason}`).join("\n\n")}`;const r=await context.env.AI.run("@cf/meta/llama-3.1-8b-instruct-fast",{prompt:ranking,temperature:0,max_tokens:500});const p=extractJsonObject(r?.response??r?.result?.response??"");if(Array.isArray(p?.indexes)){const ordered=p.indexes.map(Number).filter(i=>Number.isInteger(i)&&candidates[i]);const rest=candidates.map((_,i)=>i).filter(i=>!ordered.includes(i));candidates=[...ordered,...rest].map(i=>candidates[i]).slice(0,5);}}catch(e){console.error("Nivora PDF ranking failed:",e);}}
return Response.json({success:true,coreTopic,results:candidates.slice(0,5).map(x=>({title:x.title||"PDF resource",url:x.url,source:(()=>{try{return new URL(x.url).hostname.replace(/^www\./,"")}catch{return"Web"}})(),reason:x.reason||`Relevant to ${coreTopic}.`}))});}catch(e){console.error("Nivora PDF search error:",e);return Response.json({error:"Nivora could not search for PDF resources."},{status:500});}}
